INSERT INTO cargo (nome) VALUES ('TEC LEADER');
INSERT INTO cargo (nome) VALUES ('ANALISTA');
INSERT INTO cargo (nome) VALUES ('DESENVOLVEDOR');
INSERT INTO cargo (nome) VALUES ('TESTER');
INSERT INTO cargo (nome) VALUES ('GERENTE DE PROJETOS');
INSERT INTO cargo (nome) VALUES ('SCRUM MASTER');
INSERT INTO cargo (nome) VALUES ('PRODUCT OWNER');