CREATE TABLE USUARIO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SECRETARIA (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CARGO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE RESPONSAVEL (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    usuario_id BIGINT NOT NULL,
    secretaria_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    FOREIGN KEY (secretaria_id) REFERENCES SECRETARIA(id),
    FOREIGN KEY (cargo_id) REFERENCES CARGO(id)
);

CREATE TABLE PROJETO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    status ENUM('A_INICIAR', 'EM_ANDAMENTO', 'ATRASADO', 'CONCLUIDO') NOT NULL,
    inicio_previsto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    termino_previsto TIMESTAMP deFAULT CURRENT_TIMESTAMP,
    inicio_realizado TIMESTAMP dEFAULT CURRENT_TIMESTAMP,
    termino_realizado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dias_atraso INT DEFAULT 0,
    percentual_tempo_restante INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

CREATE TABLE PROJETO_RESPONSAVEL (
    projeto_id BIGINT NOT NULL,
    responsavel_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projeto_id) REFERENCES PROJETO(id),
    FOREIGN KEY (responsavel_id) REFERENCES RESPONSAVEL(id),
    PRIMARY KEY (projeto_id, responsavel_id)
);

INSERT INTO CARGO (nome) VALUES ('TEC LEADER');
INSERT INTO CARGO (nome) VALUES ('ANALISTA');
INSERT INTO CARGO (nome) VALUES ('DESENVOLVEDOR');
INSERT INTO CARGO (nome) VALUES ('TESTER');
INSERT INTO CARGO (nome) VALUES ('GERENTE DE PROJETOS');
INSERT INTO CARGO (nome) VALUES ('SCRUM MASTER');
INSERT INTO CARGO (nome) VALUES ('PRODUCT OWNER');