CREATE TABLE USUARIO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SECRETARIA (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CARGO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE RESPONSAVEL (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    usuario_id BIGINT NOT NULL,
    secretaria_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    FOREIGN KEY (secretaria_id) REFERENCES SECRETARIA(id),
    FOREIGN KEY (cargo_id) REFERENCES CARGO(id)
);





INSERT INTO CARGO (nome) VALUES ('TEC LEADER');
INSERT INTO CARGO (nome) VALUES ('ANALISTA');
INSERT INTO CARGO (nome) VALUES ('DESENVOLVEDOR');
INSERT INTO CARGO (nome) VALUES ('TESTER');
INSERT INTO CARGO (nome) VALUES ('GERENTE DE PROJETOS');
INSERT INTO CARGO (nome) VALUES ('SCRUM MASTER');
INSERT INTO CARGO (nome) VALUES ('PRODUCT OWNER');